version: '2.1'

services:
# ###########
# Templates
# ###########

  tests:
    # For local runs in user space.
    image: ${IMAGE}
    volumes:
      - .:/amp
      - ~/.aws:/root/.aws
      - ./docker_build/fstab:/etc/fstab
    working_dir: /amp
    entrypoint: ""
    privileged: true
    cap_add:
      - SYS_ADMIN

  tests_gh_actions:
    # For runs through GH Actions.
    extends:
      file: docker-compose.yml
      service: tests
    dns:
      - 172.31.25.168
      - 172.31.0.2
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      GOOGLE_SPREADSHEET_SECRET_API: $GOOGLE_SPREADSHEET_SECRET_API
      GOOGLE_SPREADSHEET_DEFAULT_TOKEN: $GOOGLE_SPREADSHEET_DEFAULT_TOKEN
      GOOGLE_SPREADSHEET_TYPE: $GOOGLE_SPREADSHEET_TYPE
      GOOGLE_SPREADSHEET_PROJECT_ID: $GOOGLE_SPREADSHEET_PROJECT_ID
      GOOGLE_SPREADSHEET_PRIVATE_KEY_ID: $GOOGLE_SPREADSHEET_PRIVATE_KEY_ID
      GOOGLE_SPREADSHEET_PRIVATE_KEY: $GOOGLE_SPREADSHEET_PRIVATE_KEY
      GOOGLE_SPREADSHEET_CLIENT_EMAIL: $GOOGLE_SPREADSHEET_CLIENT_EMAIL
      GOOGLE_SPREADSHEET_CLIENT_ID: $GOOGLE_SPREADSHEET_CLIENT_ID
      GOOGLE_SPREADSHEET_AUTH_URI: $GOOGLE_SPREADSHEET_AUTH_URI
      GOOGLE_SPREADSHEET_TOKEN_URI: $GOOGLE_SPREADSHEET_TOKEN_URI
      GOOGLE_SPREADSHEET_AUTH_PROVIDER_X509_CERT_URL: $GOOGLE_SPREADSHEET_AUTH_PROVIDER_X509_CERT_URL
      GOOGLE_SPREADSHEET_CLIENT_X509_CERT_URL: $GOOGLE_SPREADSHEET_CLIENT_X509_CERT_URL
    volumes:
      - .:/commodity_research

  # ###########
  # Fast tests
  # ###########
  fast_tests:
    extends:
      file: docker-compose.yml
      service: tests
    command: docker_build/run_fast_tests.sh

  fast_tests_gh_action:
    extends:
      file: docker-compose.yml
      service: tests_gh_actions
    command: docker_build/run_fast_tests_gh_action.sh

  # ###########
  # Slow tests
  # ###########

  slow_tests:
    extends:
      file: docker-compose.yml
      service: tests
    command: docker_build/run_slow_tests.sh

  slow_tests_gh_action:
    extends:
      file: docker-compose.yml
      service: tests_gh_actions
    command: docker_build/run_slow_tests_gh_action.sh

  # ###########
  # Superslow tests
  # ###########

  superslow_tests:
    extends:
      file: docker-compose.yml
      service: tests
    command: docker_build/run_superslow_tests.sh

  superslow_tests_gh_action:
    extends:
      file: docker-compose.yml
      service: tests_gh_actions
    command: docker_build/run_superslow_tests_gh_action.sh
