version: '3'
services:
  tws:
    image: ${IMAGE}
    entrypoint: "/app/entrypoint.sh"
    environment:
      - APP=${IB_APP}
      - VNC_PASSWORD=${VNC_PASSWORD}
      - TRUSTED_IPS=${TRUSTED_IPS}
      - VNC_PORT=${VNC_PORT}
      - API_PORT=${API_PORT}
      - TWSUSERID=${TWSUSERID}
      - TWSPASSWORD=${TWSPASSWORD}
    env_file:
      #- ~/.vnc/ib.credentials
      - ../env/local.env
    ports:
      - "${VNC_PORT}:${VNC_PORT}"
      - "${API_PORT}:${API_PORT}"
