# TODO(gp): docker-compose.yml is not used anywhere
# - Merge devops/compose/docker-compose-user-space*.yml with
# - Remove the current docker-compose.yml and rename
#   devops/compose/docker-compose.yml to docker-compose.yml
version: '3'

services:
  user_space:
    image: $IMAGE
    restart: "no"
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    volumes:
      # TODO(gp): Some of the volumes that are not common to `lem` and `amp`
      # should be factored out so we can use links.
      - ../..:/app
      - ~/.aws:/root/.aws
      - ~/.config/gspread_pandas/:/root/.config/gspread_pandas/
      - ~/.config/gh:/root/.config/gh
      # No need to mount file systems.
      #- ../docker_build/fstab:/etc/fstab
    privileged: true
    cap_add:
      - SYS_ADMIN
