#
# Basic setup to run as user and GitHub action.
#
version: '3'

services:
  app:
    cap_add:
      - SYS_ADMIN
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - GH_ACTION_ACCESS_TOKEN=$GH_ACTION_ACCESS_TOKEN
    image: ${IMAGE}
    privileged: true
    restart: "no"
    volumes:
      - ~/.aws:/root/.aws
      - ~/.config/gspread_pandas/:/root/.config/gspread_pandas/
      - ~/.config/gh:/root/.config/gh
      # No need to mount file systems.
      #- ../docker_build/fstab:/etc/fstab
