version: '3'

services:
  jupyter_server:
    image: $IMAGE
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: devops/docker_scripts/run_jupyter_server.sh
    extends:
      user_space 

  # TODO(gp): For some reason it doesn't work.
  #  jupyter_server_test:
  #    extends:
  #      jupyter_server
  #    command: jupyter notebook -h 2>&1 >/dev/null

  jupyter_server_test:
    image: $IMAGE
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: jupyter notebook -h 2>&1 >/dev/null
    extends:
      user_space 
