#
# Run jupyter server.
#

version: '3'

services:
  jupyter_server:
    command: devops/docker_scripts/run_jupyter_server.sh
    environment:
      - PORT=${PORT}
    extends:
      app
    ports:
      - "${PORT}:${PORT}"

  # TODO(gp): For some reason the following doesn't work.
  #  jupyter_server_test:
  #    command: jupyter notebook -h 2>&1 >/dev/null
  #    extends:
  #      jupyter_server

  jupyter_server_test:
    command: jupyter notebook -h 2>&1 >/dev/null
    environment:
      - PORT=${PORT}
    extends:
      app
    ports:
      - "${PORT}:${PORT}"
