#
# Mount `amp` when it is used as submodule. In this case we need to
# mount `lem` in the container (to make git work with the
# supermodule) and then change dir to `amp`.
#
version: '3'

services:
  app:
    volumes:
      # Move one dir up to include the entire git repo (see AmpTask1017).
      - ../../../:/app
    # Move one dir down to include the entire git repo (see AmpTask1017).
    working_dir: /app/amp
