version: '3'

services:
  user_space:
    image: $IMAGE
    restart: "no"
    volumes:
      # AmpTask1017: Move one dir up to include the entire git repo.
      - ../../../:/app
      - ~/.aws:/root/.aws
      - ~/.config/gspread_pandas/:/root/.config/gspread_pandas/
      - ../docker_build/fstab:/etc/fstab
    # AmpTask1017: Move one dir down to include the entire git repo.
    working_dir: /app/amp
    privileged: true
    cap_add:
      - SYS_ADMIN
