# This is needed only for `amp` when it is used as submodule.
# In this case we need to mount `lem` in the container (to make git work with
# the supermodule) and then change dir to `amp`.

version: '3'

services:
  user_space:
    image: $IMAGE
    restart: "no"
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    volumes:
      # Move one dir up to include the entire git repo (see AmpTask1017).
      - ../../../:/app
      - ~/.aws:/root/.aws
      - ~/.config/gspread_pandas:/root/.config/gspread_pandas
      - ~/.config/gh:/root/.config/gh
      # No need to mount file systems.
      #- ../docker_build/fstab:/etc/fstab
    # Move one dir down to include the entire git repo (see AmpTask1017).
    working_dir: /app/amp
    privileged: true
    cap_add:
      - SYS_ADMIN
