version: '3'

services:
  app:
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      GOOGLE_SPREADSHEET_SECRET_API: $GOOGLE_SPREADSHEET_SECRET_API
      GOOGLE_SPREADSHEET_DEFAULT_TOKEN: $GOOGLE_SPREADSHEET_DEFAULT_TOKEN
      GOOGLE_SPREADSHEET_TYPE: $GOOGLE_SPREADSHEET_TYPE
      GOOGLE_SPREADSHEET_PROJECT_ID: $GOOGLE_SPREADSHEET_PROJECT_ID
      GOOGLE_SPREADSHEET_PRIVATE_KEY_ID: $GOOGLE_SPREADSHEET_PRIVATE_KEY_ID
      GOOGLE_SPREADSHEET_PRIVATE_KEY: $GOOGLE_SPREADSHEET_PRIVATE_KEY
      GOOGLE_SPREADSHEET_CLIENT_EMAIL: $GOOGLE_SPREADSHEET_CLIENT_EMAIL
      GOOGLE_SPREADSHEET_CLIENT_ID: $GOOGLE_SPREADSHEET_CLIENT_ID
      GOOGLE_SPREADSHEET_AUTH_URI: $GOOGLE_SPREADSHEET_AUTH_URI
      GOOGLE_SPREADSHEET_TOKEN_URI: $GOOGLE_SPREADSHEET_TOKEN_URI
      GOOGLE_SPREADSHEET_AUTH_PROVIDER_X509_CERT_URL: $GOOGLE_SPREADSHEET_AUTH_PROVIDER_X509_CERT_URL
      GOOGLE_SPREADSHEET_CLIENT_X509_CERT_URL: $GOOGLE_SPREADSHEET_CLIENT_X509_CERT_URL

