version: '3'

services:
  app:
    image: ${IMAGE}
    container_name: im_app_local
    entrypoint: /app/vendors_amp/devops/docker_build/entrypoints/entrypoint_deploy_postgres.sh
    depends_on:
      - im_postgres_local
    env_file:
      - ../.env/local/postgres

  im_postgres_local:
    image: postgres:13
    container_name: im_postgres_local
    restart: "no"
    volumes:
      - im_postgres_data_local:/var/lib/postgresql/data
    env_file:
      - ../.env/local/postgres
    ports:
      - "5432:5432"

volumes:
  im_postgres_data_local: {}
