version: '3'

services:
  app:
    image: ${IM_IMAGE_DEV}
    container_name: im_app_local
    entrypoint: /app/instrument_master/devops/docker_build/entrypoints/entrypoint_deploy_postgres.sh
    volumes:
      - ../../../:/app
      - ~/.aws:/root/.aws
      - ~/.config/gspread_pandas/:/root/.config/gspread_pandas/
      - ../../../devops/docker_build/fstab:/etc/fstab
    env_file:
      - ../.env/local/postgres
    privileged: true
    working_dir: /app
    cap_add:
      - SYS_ADMIN

  im_postgres_local:
    image: postgres:13
    container_name: im_postgres_local
    restart: "no"
    volumes:
      - im_postgres_data_local:/var/lib/postgresql/data
    env_file:
      - ../.env/local/postgres
    ports:
      - "5432:5432"

volumes:
  im_postgres_data_local: {}