version: '3'

services:
  app:
    image: ${IMAGE}
    entrypoint: /app/instrument_master/devops/docker_build/entrypoints/entrypoint_deploy.sh
    depends_on:
      - im_postgres_test
    env_file:
      - ../env/test.env

  # TODO(gp): -> im.postgres.test:
  im_postgres_test:
    image: postgres:13
    # TODO(gp): -> Needed?
    container_name: im_postgres_test
    restart: "no"
    env_file:
      - ../env/test.env
    ports:
      - "5551:5551"
    command: "-p 5551"
