version: '3'

services:
  app:
    image: ${IMAGE}
    entrypoint: /app/instrument_master/devops/docker_build/entrypoints/entrypoint_deploy.sh
    depends_on:
      - im_postgres_local
    env_file:
      - ../env/local.env
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}

  im_postgres_local:
    image: postgres:13
    # TODO(gp): -> Needed?
    container_name: im_postgres_local
    restart: "no"
    volumes:
      - im_postgres_data_local:/var/lib/postgresql/data
    env_file:
      - ../env/local.env
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: "-p ${POSTGRES_PORT}"

volumes:
  im_postgres_data_local: {}
