name: Build image
on:
  workflow_dispatch:

jobs:
  Build_image:
    runs-on: [self-hosted, CPU4_RAM16, SLOW]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_ACTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_ACTION_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cleanup
        run: sudo chmod 777 -R .

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.GH_ACTION_SSH_PRIVATE_KEY }}

      - name: Build "rc" image
        run: make docker_build_image.rc

      - name: Push image "rc" image
        run: make docker_push_image.rc

      - name: Run fast tests for "rc" image
        if: ${{ success() }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GH_ACTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_ACTION_AWS_SECRET_ACCESS_KEY }}
        run: make run_fast_tests.gh_action_rc

      - name: Run slow tests for "rc" image
        if: ${{ success() }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GH_ACTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_ACTION_AWS_SECRET_ACCESS_KEY }}
        run: make run_slow_tests.gh_action_rc

      - name: Run superslow tests for "rc" image
        if: ${{ success() }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GH_ACTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_ACTION_AWS_SECRET_ACCESS_KEY }}
        run: make run_superslow_tests.gh_action_rc

      - name: Add "latest" tag
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        run: make docker_tag_rc_image.latest

      - name: Push "latest" image
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        run: make docker_push_image.latest

      - name: Send Telegram notification
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.P1_TG_BUILD_MONITORING_CHANNEL_ID }}
          token: ${{ secrets.P1_GH_BOT_TELEGRAM_TOKEN }}
          message: |
            A brand new image `amp_env` was successfully built.

            Please pull new image to use the latest version.
            ```
            # Authorize your client:
            make docker_login
            # Pull the latest version:
            make docker_pull
            ```
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
