name: Fast tests
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Run this once a day even if there are no commit.
    - cron:  '0 0 */1 * *'

jobs:
#  Run_fast_tests_mark_commit:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Post status if was triggered manually
#        if: ${{ github.event_name == 'workflow_dispatch' }}
#        uses: Sibz/github-status-action@v1
#        with:
#          authToken: ${{secrets.GITHUB_TOKEN}}
#          context: "Run_fast_tests"
#          description: 'Added to queue, waiting for free runner (manual run)'
#          state: pending
#          sha: ${{ github.sha }}
#          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  Mark_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Post status if was triggered manually
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Run_fast_tests"
          description: 'Added to queue, waiting for free runner (manual run)'
          state: pending
          sha: ${{ github.sha }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Cancel previous runs
        if: ${{ github.head_ref != 'master' }}
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  Run_fast_tests:
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, FAST]

    steps:
      - name: Post status if was triggered manually
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Run_fast_tests"
          description: 'Job in progress (manual run)'
          state: pending
          sha: ${{ github.sha }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_ACTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_ACTION_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cleanup
        run: sudo chmod 777 -R .

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          # TODO(gp): Not needed?
          ssh-key: ${{ secrets.GH_ACTION_SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/gh_requirements.txt

      - name: Pull image
        run: invoke docker_pull --mode="current"

      - name: Run fast tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GH_ACTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_ACTION_AWS_SECRET_ACCESS_KEY }}
        run: invoke run_fast_tests

      - name: Post status if was triggered manually
        if: ${{ always() && github.event_name == 'workflow_dispatch' }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Run_fast_tests"
          description: 'Job is done (manual run)'
          state: ${{ job.status }}
          sha: ${{ github.sha }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Send Telegram notification
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.P1_TG_BUILD_MONITORING_CHANNEL_ID }}
          token: ${{ secrets.P1_GH_BOT_TELEGRAM_TOKEN }}
          message: |
            Build failure `${{ github.workflow }}`
            Repo: ${{ github.repository }}
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send Telegram notification for failure
        if: ${{ failure() }}
        #if: ${{ failure() && github.event_name == 'schedule' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.AM_TG_BUILDBOT_CHATID }}
          token: ${{ secrets.AM_TG_BUILDBOT_TOKEN }}
          message: |
            🧨 FAST TESTS FAILED
            Build failure `${{ github.workflow }}`
            Repo: ${{ github.repository }}
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
