name: Superslow tests.
on:
  workflow_dispatch:
  schedule:
    # Run this once a day.
    - cron:  '0 0 */1 * *'

jobs:
  Run_superslow_tests_mark_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Post status if was triggered manually
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Run_superslow_tests"
          description: 'Added to queue, waiting for free runner. (Manual run)'
          state: pending
          sha: ${{ github.sha }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  Run_superslow_tests:
    runs-on: [SUPERSLOW]
    steps:
      - name: Post status if was triggered manually
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Run_superslow_tests"
          description: 'Job in progress. (Manual run)'
          state: pending
          sha: ${{ github.sha }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_ACTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_ACTION_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cleanup
        run: sudo chmod 777 -R .

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.GH_ACTION_SSH_PRIVATE_KEY }}

      - name: Pull image
        run: make docker_pull

      - name: Run superslow tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GH_ACTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_ACTION_AWS_SECRET_ACCESS_KEY }}
          GOOGLE_SPREADSHEET_SECRET_API: ${{ secrets.GOOGLE_SPREADSHEET_SECRET_API }}
          GOOGLE_SPREADSHEET_DEFAULT_TOKEN: ${{ secrets.GOOGLE_SPREADSHEET_DEFAULT_TOKEN }}
          GOOGLE_SPREADSHEET_TYPE: ${{ secrets.GOOGLE_SPREADSHEET_TYPE }}
          GOOGLE_SPREADSHEET_PROJECT_ID: ${{ secrets.GOOGLE_SPREADSHEET_PROJECT_ID }}
          GOOGLE_SPREADSHEET_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_SPREADSHEET_PRIVATE_KEY_ID }}
          GOOGLE_SPREADSHEET_PRIVATE_KEY: ${{ secrets.GOOGLE_SPREADSHEET_PRIVATE_KEY }}
          GOOGLE_SPREADSHEET_CLIENT_EMAIL: ${{ secrets.GOOGLE_SPREADSHEET_CLIENT_EMAIL }}
          GOOGLE_SPREADSHEET_CLIENT_ID: ${{ secrets.GOOGLE_SPREADSHEET_CLIENT_ID }}
          GOOGLE_SPREADSHEET_AUTH_URI: ${{ secrets.GOOGLE_SPREADSHEET_AUTH_URI }}
          GOOGLE_SPREADSHEET_TOKEN_URI: ${{ secrets.GOOGLE_SPREADSHEET_TOKEN_URI }}
          GOOGLE_SPREADSHEET_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.GOOGLE_SPREADSHEET_AUTH_PROVIDER_X509_CERT_URL }}
          GOOGLE_SPREADSHEET_CLIENT_X509_CERT_URL: ${{ secrets.GOOGLE_SPREADSHEET_CLIENT_X509_CERT_URL }}
        run: make test_superslow_gh_action

      - name: Post status if was triggered manually
        if: ${{ always() && github.event_name == 'workflow_dispatch' }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Run_superslow_tests"
          description: 'Job is done. (Manual run)'
          state: ${{ job.status }}
          sha: ${{ github.sha }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Send telegramm notification
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.P1_TG_BUILD_MONITORING_CHANNEL_ID }}
          token: ${{ secrets.P1_GH_BOT_TELEGRAM_TOKEN }}
          message: |
            Build failure 'Superslow tests'.
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
